# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: acb70438e62661fbd621a9ffa6421dcf50a98700dc1c2851e937a2c27c7398e4947821b95877bff8d20a7ee683fda81015332c2c36c1168fc132e57425f4c708

test:
  secret_key_base: 82157e552b638ff17eac09a01e308778437f7b191acce81743d746b81919565c5dfb0bcbbe6e2ef054907c3f2cfd9a6d0088fc406cf081756a9db5f6ea3eb4ca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
